# Shared development environment
fx.api.base-url=http://localhost:8080/api
fc.api.base-url=http://localhost:8080/api

# OAuth2 client_credentials
web.oauth.enabled=true
web.oauth.token-url=zzz
web.oauth.client-id=yyy
web.oauth.client-secret=xxx
web.oauth.scope=openid
web.oauth.refresh-skew-seconds=30
